-- 더미 데이터 생성 스크립트
-- 100개의 게시글 생성

-- 먼저 기존 사용자 확인 (curltest 사용자 ID를 1로 가정)
SET @user_id = 1;

-- 게시글 100개 생성
INSERT INTO posts (title, content, author_id, password, view_count, created_at, updated_at) VALUES
('Spring Boot 시작하기', 'Spring Boot는 Java 기반의 웹 애플리케이션을 쉽게 만들 수 있게 해주는 프레임워크입니다.', @user_id, 'dummy', 0, NOW() - INTERVAL 100 DAY, NOW() - INTERVAL 100 DAY),
('JPA란 무엇인가?', 'JPA는 Java Persistence API의 약자로, 자바 ORM 기술 표준입니다.', @user_id, 'dummy', 5, NOW() - INTERVAL 99 DAY, NOW() - INTERVAL 99 DAY),
('REST API 설계 원칙', 'REST API를 설계할 때 지켜야 할 중요한 원칙들에 대해 알아봅시다.', @user_id, 'dummy', 12, NOW() - INTERVAL 98 DAY, NOW() - INTERVAL 98 DAY),
('MySQL 최적화 팁', '데이터베이스 성능을 향상시키기 위한 MySQL 최적화 방법을 소개합니다.', @user_id, 'dummy', 8, NOW() - INTERVAL 97 DAY, NOW() - INTERVAL 97 DAY),
('React vs Vue 비교', '프론트엔드 프레임워크인 React와 Vue의 장단점을 비교해봅니다.', @user_id, 'dummy', 15, NOW() - INTERVAL 96 DAY, NOW() - INTERVAL 96 DAY),
('Docker 입문 가이드', 'Docker를 처음 시작하는 분들을 위한 기초 가이드입니다.', @user_id, 'dummy', 20, NOW() - INTERVAL 95 DAY, NOW() - INTERVAL 95 DAY),
('Git 브랜치 전략', 'Git Flow, GitHub Flow 등 다양한 브랜치 전략을 알아봅니다.', @user_id, 'dummy', 18, NOW() - INTERVAL 94 DAY, NOW() - INTERVAL 94 DAY),
('JavaScript ES6+ 문법', '최신 JavaScript 문법인 ES6+의 주요 기능들을 정리했습니다.', @user_id, 'dummy', 25, NOW() - INTERVAL 93 DAY, NOW() - INTERVAL 93 DAY),
('CSS Grid 레이아웃', 'CSS Grid를 사용한 현대적인 레이아웃 구성 방법입니다.', @user_id, 'dummy', 10, NOW() - INTERVAL 92 DAY, NOW() - INTERVAL 92 DAY),
('TypeScript 기초', 'TypeScript의 기본 개념과 타입 시스템에 대해 알아봅니다.', @user_id, 'dummy', 14, NOW() - INTERVAL 91 DAY, NOW() - INTERVAL 91 DAY),
('Node.js 비동기 처리', 'Node.js에서 비동기 처리를 다루는 다양한 방법들을 소개합니다.', @user_id, 'dummy', 22, NOW() - INTERVAL 90 DAY, NOW() - INTERVAL 90 DAY),
('MongoDB vs MySQL', 'NoSQL과 RDBMS의 차이점과 각각의 사용 사례를 비교합니다.', @user_id, 'dummy', 16, NOW() - INTERVAL 89 DAY, NOW() - INTERVAL 89 DAY),
('웹 보안 기초', 'XSS, CSRF 등 웹 애플리케이션의 주요 보안 취약점을 알아봅니다.', @user_id, 'dummy', 30, NOW() - INTERVAL 88 DAY, NOW() - INTERVAL 88 DAY),
('Redis 캐싱 전략', 'Redis를 활용한 효과적인 캐싱 전략을 소개합니다.', @user_id, 'dummy', 19, NOW() - INTERVAL 87 DAY, NOW() - INTERVAL 87 DAY),
('Kubernetes 기초', '컨테이너 오케스트레이션 도구인 Kubernetes의 기본 개념입니다.', @user_id, 'dummy', 28, NOW() - INTERVAL 86 DAY, NOW() - INTERVAL 86 DAY),
('GraphQL 소개', 'REST API의 대안으로 떠오르는 GraphQL에 대해 알아봅니다.', @user_id, 'dummy', 21, NOW() - INTERVAL 85 DAY, NOW() - INTERVAL 85 DAY),
('마이크로서비스 아키텍처', '마이크로서비스 아키텍처의 장단점과 구현 방법을 다룹니다.', @user_id, 'dummy', 35, NOW() - INTERVAL 84 DAY, NOW() - INTERVAL 84 DAY),
('CI/CD 파이프라인', '지속적 통합과 배포를 위한 CI/CD 파이프라인 구축 방법입니다.', @user_id, 'dummy', 26, NOW() - INTERVAL 83 DAY, NOW() - INTERVAL 83 DAY),
('TDD 실천하기', '테스트 주도 개발(TDD)의 개념과 실천 방법을 소개합니다.', @user_id, 'dummy', 17, NOW() - INTERVAL 82 DAY, NOW() - INTERVAL 82 DAY),
('클린 코드 원칙', '읽기 좋고 유지보수하기 쉬운 코드를 작성하는 방법입니다.', @user_id, 'dummy', 40, NOW() - INTERVAL 81 DAY, NOW() - INTERVAL 81 DAY),
('디자인 패턴 정리', 'GoF의 23가지 디자인 패턴을 정리하고 예제를 제공합니다.', @user_id, 'dummy', 33, NOW() - INTERVAL 80 DAY, NOW() - INTERVAL 80 DAY),
('AWS 서비스 소개', 'Amazon Web Services의 주요 서비스들을 소개합니다.', @user_id, 'dummy', 24, NOW() - INTERVAL 79 DAY, NOW() - INTERVAL 79 DAY),
('Python Django 시작하기', 'Python 웹 프레임워크인 Django로 웹 개발을 시작해봅시다.', @user_id, 'dummy', 29, NOW() - INTERVAL 78 DAY, NOW() - INTERVAL 78 DAY),
('Flutter 모바일 앱 개발', 'Flutter를 사용한 크로스 플랫폼 모바일 앱 개발 가이드입니다.', @user_id, 'dummy', 31, NOW() - INTERVAL 77 DAY, NOW() - INTERVAL 77 DAY),
('Webpack 설정하기', '모던 웹 개발을 위한 Webpack 설정 방법을 알아봅니다.', @user_id, 'dummy', 13, NOW() - INTERVAL 76 DAY, NOW() - INTERVAL 76 DAY),
('Nginx 웹 서버 설정', 'Nginx를 사용한 웹 서버 구축과 설정 방법입니다.', @user_id, 'dummy', 27, NOW() - INTERVAL 75 DAY, NOW() - INTERVAL 75 DAY),
('OAuth 2.0 인증', 'OAuth 2.0 인증 프로토콜의 동작 원리를 설명합니다.', @user_id, 'dummy', 23, NOW() - INTERVAL 74 DAY, NOW() - INTERVAL 74 DAY),
('Elasticsearch 검색 엔진', 'Elasticsearch를 활용한 강력한 검색 기능 구현 방법입니다.', @user_id, 'dummy', 36, NOW() - INTERVAL 73 DAY, NOW() - INTERVAL 73 DAY),
('RabbitMQ 메시지 큐', '메시지 큐 시스템인 RabbitMQ의 기본 개념과 사용법입니다.', @user_id, 'dummy', 20, NOW() - INTERVAL 72 DAY, NOW() - INTERVAL 72 DAY),
('Prometheus 모니터링', '시스템 모니터링을 위한 Prometheus 사용 가이드입니다.', @user_id, 'dummy', 25, NOW() - INTERVAL 71 DAY, NOW() - INTERVAL 71 DAY),
('Kafka 스트림 처리', 'Apache Kafka를 사용한 실시간 데이터 스트림 처리입니다.', @user_id, 'dummy', 32, NOW() - INTERVAL 70 DAY, NOW() - INTERVAL 70 DAY),
('Terraform 인프라 코드', 'Infrastructure as Code를 위한 Terraform 사용법입니다.', @user_id, 'dummy', 28, NOW() - INTERVAL 69 DAY, NOW() - INTERVAL 69 DAY),
('Jenkins 자동화', 'Jenkins를 활용한 빌드 및 배포 자동화 구축 방법입니다.', @user_id, 'dummy', 22, NOW() - INTERVAL 68 DAY, NOW() - INTERVAL 68 DAY),
('Ansible 설정 관리', '서버 설정 관리 도구인 Ansible의 기본 사용법입니다.', @user_id, 'dummy', 19, NOW() - INTERVAL 67 DAY, NOW() - INTERVAL 67 DAY),
('Grafana 대시보드', '데이터 시각화 도구 Grafana로 대시보드를 만드는 방법입니다.', @user_id, 'dummy', 26, NOW() - INTERVAL 66 DAY, NOW() - INTERVAL 66 DAY),
('Selenium 테스트 자동화', '웹 애플리케이션 테스트 자동화를 위한 Selenium 가이드입니다.', @user_id, 'dummy', 21, NOW() - INTERVAL 65 DAY, NOW() - INTERVAL 65 DAY),
('Jest 단위 테스트', 'JavaScript 테스트 프레임워크 Jest 사용법을 알아봅니다.', @user_id, 'dummy', 18, NOW() - INTERVAL 64 DAY, NOW() - INTERVAL 64 DAY),
('Cypress E2E 테스트', 'End-to-End 테스트를 위한 Cypress 프레임워크입니다.', @user_id, 'dummy', 24, NOW() - INTERVAL 63 DAY, NOW() - INTERVAL 63 DAY),
('Postman API 테스트', 'API 개발과 테스트를 위한 Postman 활용법입니다.', @user_id, 'dummy', 15, NOW() - INTERVAL 62 DAY, NOW() - INTERVAL 62 DAY),
('Swagger API 문서화', 'API 문서 자동화를 위한 Swagger 사용 가이드입니다.', @user_id, 'dummy', 20, NOW() - INTERVAL 61 DAY, NOW() - INTERVAL 61 DAY),
('Jira 프로젝트 관리', '애자일 프로젝트 관리 도구 Jira 사용법을 소개합니다.', @user_id, 'dummy', 17, NOW() - INTERVAL 60 DAY, NOW() - INTERVAL 60 DAY),
('Slack 협업 도구', '팀 커뮤니케이션 도구 Slack의 효과적인 활용 방법입니다.', @user_id, 'dummy', 12, NOW() - INTERVAL 59 DAY, NOW() - INTERVAL 59 DAY),
('Notion 문서 관리', '올인원 워크스페이스 Notion으로 문서를 관리하는 방법입니다.', @user_id, 'dummy', 16, NOW() - INTERVAL 58 DAY, NOW() - INTERVAL 58 DAY),
('VS Code 확장 프로그램', '생산성을 높이는 VS Code 필수 확장 프로그램들입니다.', @user_id, 'dummy', 30, NOW() - INTERVAL 57 DAY, NOW() - INTERVAL 57 DAY),
('IntelliJ IDEA 단축키', 'IntelliJ IDEA의 유용한 단축키와 팁을 정리했습니다.', @user_id, 'dummy', 25, NOW() - INTERVAL 56 DAY, NOW() - INTERVAL 56 DAY),
('Chrome DevTools 활용', '웹 개발을 위한 Chrome 개발자 도구 활용법입니다.', @user_id, 'dummy', 22, NOW() - INTERVAL 55 DAY, NOW() - INTERVAL 55 DAY),
('Figma 디자인 도구', 'UI/UX 디자인 협업 도구 Figma 사용 가이드입니다.', @user_id, 'dummy', 19, NOW() - INTERVAL 54 DAY, NOW() - INTERVAL 54 DAY),
('Tailwind CSS 유틸리티', '유틸리티 우선 CSS 프레임워크 Tailwind CSS 소개입니다.', @user_id, 'dummy', 28, NOW() - INTERVAL 53 DAY, NOW() - INTERVAL 53 DAY),
('Bootstrap 반응형 디자인', 'Bootstrap을 활용한 반응형 웹 디자인 구현 방법입니다.', @user_id, 'dummy', 14, NOW() - INTERVAL 52 DAY, NOW() - INTERVAL 52 DAY),
('Material-UI 컴포넌트', 'React Material-UI 컴포넌트 라이브러리 사용법입니다.', @user_id, 'dummy', 21, NOW() - INTERVAL 51 DAY, NOW() - INTERVAL 51 DAY),
('Sass/SCSS 전처리기', 'CSS 전처리기 Sass의 기능과 사용법을 알아봅니다.', @user_id, 'dummy', 17, NOW() - INTERVAL 50 DAY, NOW() - INTERVAL 50 DAY),
('Styled Components', 'CSS-in-JS 라이브러리 Styled Components 가이드입니다.', @user_id, 'dummy', 23, NOW() - INTERVAL 49 DAY, NOW() - INTERVAL 49 DAY),
('Redux 상태 관리', 'React 애플리케이션의 상태 관리를 위한 Redux 사용법입니다.', @user_id, 'dummy', 26, NOW() - INTERVAL 48 DAY, NOW() - INTERVAL 48 DAY),
('MobX 상태 관리', 'Redux의 대안인 MobX 상태 관리 라이브러리입니다.', @user_id, 'dummy', 18, NOW() - INTERVAL 47 DAY, NOW() - INTERVAL 47 DAY),
('Zustand 경량 상태 관리', '간단하고 빠른 상태 관리 라이브러리 Zustand입니다.', @user_id, 'dummy', 20, NOW() - INTERVAL 46 DAY, NOW() - INTERVAL 46 DAY),
('React Query 데이터 페칭', '서버 상태 관리를 위한 React Query 사용 가이드입니다.', @user_id, 'dummy', 24, NOW() - INTERVAL 45 DAY, NOW() - INTERVAL 45 DAY),
('SWR 데이터 페칭', 'Vercel의 SWR 라이브러리로 데이터를 효율적으로 관리합니다.', @user_id, 'dummy', 19, NOW() - INTERVAL 44 DAY, NOW() - INTERVAL 44 DAY),
('Next.js SSR/SSG', 'Next.js의 서버 사이드 렌더링과 정적 생성 방법입니다.', @user_id, 'dummy', 32, NOW() - INTERVAL 43 DAY, NOW() - INTERVAL 43 DAY),
('Nuxt.js Vue 프레임워크', 'Vue.js 기반의 Nuxt.js 프레임워크 소개입니다.', @user_id, 'dummy', 22, NOW() - INTERVAL 42 DAY, NOW() - INTERVAL 42 DAY),
('Gatsby 정적 사이트', 'React 기반 정적 사이트 생성기 Gatsby 가이드입니다.', @user_id, 'dummy', 16, NOW() - INTERVAL 41 DAY, NOW() - INTERVAL 41 DAY),
('Vite 빌드 도구', '차세대 프론트엔드 빌드 도구 Vite 사용법입니다.', @user_id, 'dummy', 25, NOW() - INTERVAL 40 DAY, NOW() - INTERVAL 40 DAY),
('Svelte 프레임워크', '컴파일 기반 프론트엔드 프레임워크 Svelte입니다.', @user_id, 'dummy', 21, NOW() - INTERVAL 39 DAY, NOW() - INTERVAL 39 DAY),
('Angular 프레임워크', 'Google의 Angular 프레임워크 기초 가이드입니다.', @user_id, 'dummy', 18, NOW() - INTERVAL 38 DAY, NOW() - INTERVAL 38 DAY),
('Solid.js 반응형 UI', '성능에 최적화된 Solid.js 프레임워크 소개입니다.', @user_id, 'dummy', 15, NOW() - INTERVAL 37 DAY, NOW() - INTERVAL 37 DAY),
('Astro 정적 사이트', '콘텐츠 중심 웹사이트를 위한 Astro 프레임워크입니다.', @user_id, 'dummy', 19, NOW() - INTERVAL 36 DAY, NOW() - INTERVAL 36 DAY),
('Remix 풀스택 프레임워크', 'React Router 팀의 Remix 프레임워크 가이드입니다.', @user_id, 'dummy', 23, NOW() - INTERVAL 35 DAY, NOW() - INTERVAL 35 DAY),
('Prisma ORM', '차세대 Node.js ORM인 Prisma 사용법을 알아봅니다.', @user_id, 'dummy', 27, NOW() - INTERVAL 34 DAY, NOW() - INTERVAL 34 DAY),
('Sequelize ORM', 'Node.js의 대표적인 ORM Sequelize 가이드입니다.', @user_id, 'dummy', 20, NOW() - INTERVAL 33 DAY, NOW() - INTERVAL 33 DAY),
('TypeORM 타입스크립트', 'TypeScript 기반 ORM인 TypeORM 사용법입니다.', @user_id, 'dummy', 22, NOW() - INTERVAL 32 DAY, NOW() - INTERVAL 32 DAY),
('Drizzle ORM', '경량 TypeScript ORM Drizzle 소개입니다.', @user_id, 'dummy', 17, NOW() - INTERVAL 31 DAY, NOW() - INTERVAL 31 DAY),
('Supabase 백엔드', 'Firebase 대안 Supabase로 백엔드를 구축하는 방법입니다.', @user_id, 'dummy', 29, NOW() - INTERVAL 30 DAY, NOW() - INTERVAL 30 DAY),
('Firebase 실시간 DB', 'Google Firebase의 실시간 데이터베이스 사용 가이드입니다.', @user_id, 'dummy', 24, NOW() - INTERVAL 29 DAY, NOW() - INTERVAL 29 DAY),
('Vercel 배포', 'Next.js 애플리케이션을 Vercel에 배포하는 방법입니다.', @user_id, 'dummy', 26, NOW() - INTERVAL 28 DAY, NOW() - INTERVAL 28 DAY),
('Netlify 정적 호스팅', '정적 웹사이트를 Netlify에 호스팅하는 가이드입니다.', @user_id, 'dummy', 21, NOW() - INTERVAL 27 DAY, NOW() - INTERVAL 27 DAY),
('Heroku 클라우드 플랫폼', 'Heroku를 사용한 애플리케이션 배포 방법입니다.', @user_id, 'dummy', 18, NOW() - INTERVAL 26 DAY, NOW() - INTERVAL 26 DAY),
('DigitalOcean VPS', 'DigitalOcean에서 VPS를 설정하고 관리하는 방법입니다.', @user_id, 'dummy', 20, NOW() - INTERVAL 25 DAY, NOW() - INTERVAL 25 DAY),
('Cloudflare CDN', 'Cloudflare CDN으로 웹사이트 성능을 향상시키는 방법입니다.', @user_id, 'dummy', 25, NOW() - INTERVAL 24 DAY, NOW() - INTERVAL 24 DAY),
('GitHub Actions CI/CD', 'GitHub Actions를 활용한 CI/CD 파이프라인 구축입니다.', @user_id, 'dummy', 30, NOW() - INTERVAL 23 DAY, NOW() - INTERVAL 23 DAY),
('GitLab CI/CD', 'GitLab의 CI/CD 기능을 활용한 자동화 가이드입니다.', @user_id, 'dummy', 22, NOW() - INTERVAL 22 DAY, NOW() - INTERVAL 22 DAY),
('Bitbucket 파이프라인', 'Bitbucket Pipelines로 CI/CD를 구성하는 방법입니다.', @user_id, 'dummy', 16, NOW() - INTERVAL 21 DAY, NOW() - INTERVAL 21 DAY),
('CircleCI 지속적 통합', 'CircleCI를 사용한 지속적 통합 설정 가이드입니다.', @user_id, 'dummy', 19, NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 20 DAY),
('Travis CI 자동화', 'Travis CI로 빌드와 테스트를 자동화하는 방법입니다.', @user_id, 'dummy', 15, NOW() - INTERVAL 19 DAY, NOW() - INTERVAL 19 DAY),
('SonarQube 코드 품질', '코드 품질 분석 도구 SonarQube 사용 가이드입니다.', @user_id, 'dummy', 23, NOW() - INTERVAL 18 DAY, NOW() - INTERVAL 18 DAY),
('ESLint 코드 린팅', 'JavaScript 코드 린팅 도구 ESLint 설정 방법입니다.', @user_id, 'dummy', 20, NOW() - INTERVAL 17 DAY, NOW() - INTERVAL 17 DAY),
('Prettier 코드 포맷팅', '코드 포맷터 Prettier로 일관된 코드 스타일을 유지합니다.', @user_id, 'dummy', 18, NOW() - INTERVAL 16 DAY, NOW() - INTERVAL 16 DAY),
('Husky Git Hooks', 'Git Hooks를 쉽게 관리하는 Husky 사용법입니다.', @user_id, 'dummy', 21, NOW() - INTERVAL 15 DAY, NOW() - INTERVAL 15 DAY),
('Commitlint 커밋 규칙', '커밋 메시지 규칙을 강제하는 Commitlint 가이드입니다.', @user_id, 'dummy', 17, NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 14 DAY),
('Semantic Release', '자동 버전 관리를 위한 Semantic Release 사용법입니다.', @user_id, 'dummy', 19, NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 13 DAY),
('Changesets 모노레포', '모노레포 버전 관리 도구 Changesets 소개입니다.', @user_id, 'dummy', 16, NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 12 DAY),
('Turborepo 빌드 시스템', '고성능 모노레포 빌드 시스템 Turborepo입니다.', @user_id, 'dummy', 22, NOW() - INTERVAL 11 DAY, NOW() - INTERVAL 11 DAY),
('Nx 모노레포 도구', '엔터프라이즈급 모노레포 도구 Nx 사용 가이드입니다.', @user_id, 'dummy', 20, NOW() - INTERVAL 10 DAY, NOW() - INTERVAL 10 DAY),
('Lerna 패키지 관리', '다중 패키지 관리를 위한 Lerna 사용법입니다.', @user_id, 'dummy', 15, NOW() - INTERVAL 9 DAY, NOW() - INTERVAL 9 DAY),
('pnpm 패키지 매니저', '빠르고 효율적인 패키지 매니저 pnpm 소개입니다.', @user_id, 'dummy', 24, NOW() - INTERVAL 8 DAY, NOW() - INTERVAL 8 DAY),
('Yarn Berry PnP', 'Yarn Berry의 Plug\'n\'Play 기능 가이드입니다.', @user_id, 'dummy', 18, NOW() - INTERVAL 7 DAY, NOW() - INTERVAL 7 DAY),
('npm 스크립트 활용', 'npm scripts를 효과적으로 활용하는 방법입니다.', @user_id, 'dummy', 21, NOW() - INTERVAL 6 DAY, NOW() - INTERVAL 6 DAY),
('Storybook 컴포넌트', 'UI 컴포넌트 개발 도구 Storybook 사용 가이드입니다.', @user_id, 'dummy', 25, NOW() - INTERVAL 5 DAY, NOW() - INTERVAL 5 DAY),
('Chromatic 비주얼 테스트', 'Storybook과 함께 사용하는 Chromatic 비주얼 테스트입니다.', @user_id, 'dummy', 19, NOW() - INTERVAL 4 DAY, NOW() - INTERVAL 4 DAY),
('Percy 스크린샷 테스트', '자동 스크린샷 테스트 도구 Percy 사용법입니다.', @user_id, 'dummy', 17, NOW() - INTERVAL 3 DAY, NOW() - INTERVAL 3 DAY),
('Playwright E2E 테스트', '크로스 브라우저 테스트 도구 Playwright 가이드입니다.', @user_id, 'dummy', 23, NOW() - INTERVAL 2 DAY, NOW() - INTERVAL 2 DAY),
('Puppeteer 자동화', 'Chrome 자동화 라이브러리 Puppeteer 사용법입니다.', @user_id, 'dummy', 20, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY);

-- 생성된 게시글 수 확인
SELECT COUNT(*) as total_posts FROM posts;
